### ISSUE TITLE
Roadmap to upgrade to yarn v2

### ISSUE THREAD

**Issue by pixelastic** [pixelastic/aberlaas#93]
## What

`aberlaas` is a tool to abstract the most common dev tasks under one module. 

I was tired of having to install and configure Jest, Prettier, ESLint, Stylelint, Husky, lint-staged, etc every time I started a new project. So I packaged all those dependencies (and their plugins and configuration) under the `aberlaas` umbrella. `yarn add aberlaas --dev` is all I need now.

Calling `aberlaas lint`, for example, will lint all files of my project. `.js` files will go through ESLint, `.css` through Stylelint, `.yml` through yamllint, etc. Same goes for `aberlaas test` that will run Jest. `aberlaas` calls some of those tools through their JavaScript API, and others through their CLI interface (some tools only have a CLI, some only have an API).

I didn't want to completely shadow the internal tools, though. I wanted to still be able to call `eslint`, `jest` or `prettier` directly from the root of the project that depends on `aberlaas`.

The (opinionated) configuration for all those tools is included in `aberlaas`. I didn't want to shadow the configuration too much either; I still wanted to be able to edit the `.eslintrc.js` or `.prettierrc.js` at the project root and have my changes be merged with the `aberlaas` default.

All of the above (and a few more commands) currently works when using yarn v1, but most everything breaks when moving to yarn v2.

### Only direct binaries are available

With yarn 2, only binaries of direct dependencies are available from a project root. If my project depends on `aberlaas`, it will have the `aberlaas` binary available, but `eslint`, `jest` and others won't be exposed. This means that by installing only `aberlaas` I no longer have direct access to the tools it's using.

In theory, I like this approach as you can really control what binaries will be available. I tried to explicitly add an `eslint` script to my `package.json > bin` field and forward the call to the underlying `eslint` binary but could not find a way to call the original `eslint`. Funnily enough `yarn bin eslint` from my custom `eslint` returned the path to itself (which is logical, but I couldn't find a way to bypass this).

### Is it possible / safe to call `yarn run` from `yarn run`?

Many internal calls of `aberlaas` relies on calling `yarn bin` to get the path to a binary, then calling this binary. This approach no longer works with yarn 2 (files are in a zip file and directly calling them won't work). The suggested approach is to call `yarn run eslint` instead.

So this would mean that in my project I would call `yarn run lint`, which will find the `scripts.lint` entry of my package.json. This will in turn run `aberlaas lint`, which in turn will run `yarn run eslint`.

I tried this, and it resulted in 100% usage of my CPU and no results displayed. I'm still not sure where it's coming from and it might not only be related to the way I call ESLint but maybe also to the way I'm requiring plugins and various configuration.

I'm also pretty confused as "which" yarn will run the second call. Is that the yarn that was running the initial call in the top level root, or will it be the yarn defined in the `aberlaas` project (through policies and `.yarn/releases`). This might not be an issue with released packages that won't have those files, but could be when using `yarn link` / `portal:`.

## Conclusion

Considering the goal of `aberlaas` (one dev dependency to rule them all), how would you approach upgrading the project to yarn 2?

**Comment by merceyz** [comment]
> Many internal calls of aberlaas relies on calling yarn bin to get the path to a binary, then calling this binary. This approach no longer works with yarn 2 (files are in a zip file and directly calling them won't work). The suggested approach is to call yarn run eslint instead.

Assming you mean spawning the scripts you can do this without a problem, you just have to spawn it using `node` and not the script path directly.

**Comment by pixelastic** [comment]
@merceyz Thanks for chiming in. I'm not sure I'm following what you suggest, though.

For example, `aberlaas` needs to run `stylelint` with custom arguments. What I do is finding the path to the `stylelint` binary by running `yarn bin stylelint` in the project, then calling `{path_to_stylelint} --arg1 --arg2 --arg3`.

From my understanding `yarn bin stylelint` in v2 will not return a path to an executable, because it's part of a zip file, so running it won't work. Or do you mean running `node {path_to_stylelint} --arg1 --arg2 --arg3` would work?

**Comment by merceyz** [comment]
> Or do you mean running node {path_to_stylelint} --arg1 --arg2 --arg3 would work?

Yes, this is what I meant

**Comment by pixelastic** [comment]
Oh ok, thanks, I thought the shebang at the top of the file would be cross-platform. Thanks!
